Fixed top and bottom borders being to large
WillPower3309/swayfx pull request #81
Opened 2023-01-01 17:00 UTC by ErikReider

The top and bottom borders were to wide which would intersect with the corners (especially with large borders)

Without:
![image](https://user-images.githubusercontent.com/35975961/210178902-9471ec9f-9e59-46d0-9244-f42e9042f34c.png)

With:
![image](https://user-images.githubusercontent.com/35975961/210178894-6dae882c-b3ac-4908-a682-80cfa07bcf86.png)

2023-01-01 18:25 UTC, WillPower3309 commented
LGTM, can you confirm that it also looks fine when corner radius is 0?

2023-01-01 18:30 UTC, ErikReider commented
> LGTM, can you confirm that it also looks fine when corner radius is 0?

Woops... Nice catch! Fixed now 😅

2023-01-01 21:32 UTC, WillPower3309 requested changes
Other than the placement of the sizing changes, LGTM

2023-01-01 21:32 UTC, WillPower3309 commented on sway/desktop/render.c
> +
Move this to the conditional block directly below

2023-01-01 21:32 UTC, WillPower3309 commented on sway/desktop/render.c
> +		}
Move this to the condiitonal block directly below

2023-01-02 17:51 UTC, ErikReider commented
> Other than the placement of the sizing changes, LGTM

That's what I get for coding late at night with foggy brain

2023-01-02 21:16 UTC, WillPower3309 approved these changes

2023-01-02 21:17 UTC, merged