Hide separator between titlebar and content
WillPower3309/swayfx pull request #91
Opened 2023-01-10 17:29 UTC by head-gardener

Solves #70.
Toggled via separate_titlebar yes|no, where no hides the separator. Might be a little confusing but I couldn't think of a better command, so this is open for discussion.

![image](https://user-images.githubusercontent.com/49650767/211620530-b59d3505-57e5-41b7-b049-a1e3c0fcc773.png)

2023-01-10 23:17 UTC, WillPower3309 commented
Good stuff! Before I can merge this I'll have to request that you match the indentation

2023-01-11 07:15 UTC, head-gardener commented
Thought i fixed that earlier. Should be ok now.

2023-01-11 07:52 UTC, WillPower3309 commented on sway/desktop/render.c
> +  }
Needs proper indentation

2023-01-11 07:52 UTC, WillPower3309 requested changes
LGTM! Just one more indentation fix needed

2023-01-11 08:48 UTC, head-gardener commented
Done. Thanks for your patience.

2023-01-15 19:40 UTC, WillPower3309 commented
Thanks for all the work here! Finally have some time today to do some testing with this branch, stay tuned :)

2023-01-16 14:43 UTC, RicArch97 commented
Thanks for the implementation. For the command we could think about changing to `separate_titlebar_border` command as it specifically applies to the border, or perhaps `titlebar_border_separator yes|no` as we should make clear what this does, remove the border between the view and titlebar.

2023-01-17 20:02 UTC, head-gardener commented
Second one seems to be more intuitive.

2023-01-27 07:02 UTC, WillPower3309 commented
Just wanted to say this will definitely get merged but I'd like to fix https://github.com/WillPower3309/swayfx/issues/96 first before making any other changes to render.c

2023-03-06 18:12 UTC, head-gardener commented on sway/desktop/shaders/corner_texture.frag
> +}
yup, my bad

2023-03-11 04:31 UTC, RicArch97 commented
Just tested this PR and got  a  **transparent** line of pixels on left side my alacritty window;

![2023-03-11T05:28:03,635515191+01:00](https://user-images.githubusercontent.com/61013287/224464919-3fe1c7af-a5b4-435d-a9a2-a942f4717cf8.png)

2023-03-11 04:33 UTC, RicArch97 commented
Also you should probably add an entry of the new option to the man page

2023-03-11 04:56 UTC, head-gardener commented
> @WillPower3309 Any idea if this has something do with the other effects (shadows / rounded corners)? Can't really see how these changes would cause this.
This PR just prevents sway from rendering lower title bar border, so if it doesn't scale background elements correctly some areas will become empty. Issue on your screenshot is with the left pad, which I must have missed because my title textures where aligned to the left. Going to check now to see if that's the problem.
> You should probably add an entry of the new option to the man page.
Honestly I've missed that we had one. Right on it.

2023-03-11 05:57 UTC, head-gardener commented
@RicArch97 can you confirm the issue is fixed?

2023-03-12 03:09 UTC, RicArch97 requested changes
Left a few more comments, rest LGTM

2023-03-12 03:09 UTC, RicArch97 commented on sway/commands/titlebar_separator.c
> +		config->titlebar_separator = true;
I believe this should be reversed. Setting `titlebar_separator enable` now disables of the separator, which might not make sense to the user. I had it set `disable` on my first test and was wondering why the separator was still there.

2023-03-12 03:09 UTC, RicArch97 commented on sway/desktop/render.c
> +	int bottom_border_compensation = config->titlebar_separator ? 0 : titlebar_border_thickness ;
redundant space between `titlebar_border_thickness` and `;`

2023-03-12 03:09 UTC, RicArch97 commented on sway/sway.5.scd
> +*titlebar_sepparator* enable|disable
typo: sepparator -> separator

2023-03-12 03:11 UTC, RicArch97 commented
In terms of functionality it's good now. Here's an updated screenshot:

![2023-03-12T03:58:01,237501836+01:00](https://user-images.githubusercontent.com/61013287/224522069-69729e0b-f4a5-4a6f-97eb-3d1ac704d8f1.png)

2023-03-12 07:20 UTC, WillPower3309 approved these changes

2023-03-12 07:20 UTC, merged